var textos = {
    conocimJs: "<p>Conocimiento de las bases del lenguaje de programación Javascript</p><p>Uso de funcionalidades propias de Ecmascript 6</p><p>Uso de la librería JQuery, AJAX y programación modular</p>",
    conocimNodeJs: " <p>Conocimiento del funcionamiento de NodeJs</p><p>Manejo del framework <em>Express</em></p><p>Modelo-Vista-Controlador (MVC)</p><p>Conocimiento de las herramientas <em>Express session</em>, <em>Nodemailer</em>, <em>Multer</em>, <em>Sequelize</em> para su uso con Express</p><p>Creación de API Rest con Express</p><p>Handlebars</p>",
    conocimHtml: "<p>Manejo de las etiquetas propias de HTML5, así como de versiones anteriores</p><p>Conocimiento básico de canvas</p><p>Conocimiento básico de posicionamiento web</p>",
    conocimCss: "<p>Conocimiento medio de las funcionalidades de CSS3, así como de versiones anteriores</p><p>Uso de CSS preprocesado (SASS)</p><p>Trabajo con <em>responsive design</em>, mediante media queries y mediante Bootstrap</p><p>Aplicaciones utilizadas: Compass, Scout-app</p>",
    conocimPhp: "<p>Conocimiento de las bases de PHP y PHP orientado a objetos</p><p>Acceso a bases de datos y manejo de resultsets</p><p>Conozco el modelo-vista-controlador (MVC) y sé aplicarlo</p>",
    conocimMysql: "<p>Sé efectuar operaciones básicas (obtener, actualizar, crear y eliminar datos), así como transacciones/rollbacks</p><p>Creación y manejo de procedimientos, funciones y <em>triggers</em></p><p>Aplicaciones utilizadas: phpMyAdmin, MySql Workbench, Toad, cmd</p>",
    conocimJava: "<p>Conocimiento de las bases del lenguaje Java, programación orientada a objetos, abstracción y manejo de interfaces</p><p>Trabajo con servlets</p><p>Uso de JSPs (Java Server Pages)</p><p>Conexión con bases de datos y manejo de resultsets</p><p>Aplicación del modelo-vista-controlador (MVC)</p>",
    contactoDirMail: "rauldelapaznavarro@gmail.com"
};